from enum import Enum


class EJobType(str, Enum):
    DOWNLOAD = "DOWNLOAD"
    INGESTION = "INGESTION"
    ETL_POPULARITY = "POPULARITY"
    ETL_SENTIMENT = "SENTIMENT"
    ETL_EMOTION = "EMOTION"
    ETL_VECTORIZATION = "VECTORIZATION"
    ETL_REDUCTION = "REDUCTION"
